//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace forget_Password.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_login
    {
        public int R_id { get; set; }
        public string R_name { get; set; }
        public string R_email { get; set; }
        public string R_password { get; set; }
        public string Confirm_pasword { get; set; }
    }
}
